### PR TITLE
Wal e

### PR DESCRIPTION
**Pull request by jharveysmith**
@mbautin

### CODE REVIEW

**Comment by mbautin** [comment]
The default recipe should probably be included by recipes that are actually being used (the attributes file is always loaded, so that's the expectation).

**Comment by jharveysmith** [comment]
Ah, good catch, the server recipe pull the client recipe directly rather than default, will fix.

**Comment by jharveysmith** [comment]
Lots of files changed.

**Comment by ScoAnderson** [comment]
I'm hoping to all high heck that Wal e helps to take out the trash!

**Pull request merged**
